version: "3.9"
services:
  guardiao-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardiao-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./state:/app/state
    command: >
      uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}