services:
  - type: web
    name: bacbo-g0-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: TZ
        value: America/Sao_Paulo
      # Adicione as outras envs no painel por segurança