services:
  - type: web
    name: guardiao-risco-bot-2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
      - key: TZ
        value: America/Sao_Paulo
      - key: TIPMINER_URL
        value: https://www.tipminer.com/br/historico/jonbet/bac-bo
      - key: FALLBACK_URL
        value: https://casinoscores.com/pt-br/bac-bo/
      - key: REQUIRE_EXTERNAL_CONFIRM
        value: "1"
      - key: GREEN_RULE
        value: opposite
      - key: HEARTBEAT_SEC
        value: "3"
      - key: AUTO_OPEN_INTERVAL_SEC
        value: "2"
      - key: RULES_ENABLED
        value: "1"
      - key: RULES_MAX_GALES
        value: "2"
      - key: RULES_COOLDOWN_ROUNDS
        value: "3"
      - key: USE_PLAYWRIGHT
        value: "0"